Transform: AWS::Serverless-2016-10-31
Description: Trigger Node.js Lambda function from API

Resources:
# api gateway
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: dm-pa-apigateway
      StageName: Prod

# lambda 
  MyNodeLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway 
            Path: /test
            Method: get