Transform: AWS::Serverless-2016-10-31
Description: Trigger Node.js Lambda function from API

Parameters:
  DeployHelloService:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /my-app/flags/hello-enabled

  DeployRandomService:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /my-app/flags/random-enabled

Conditions:
  ShouldDeployHello: !Equals [!Ref DeployHelloService, "true"]
  ShouldDeployRandom: !Equals [!Ref DeployRandomService, "true"]

Resources:
# api gateway
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: dm-pa-apigateway
      StageName: Prod
  

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dm-pa-lambda-layer
      ContentUri: package-layer/
      CompatibleRuntimes:
        - nodejs20.x

  HelloFunction:
    Type: AWS::Serverless::Function
    Condition: ShouldDeployHello
    Properties:
      Runtime: nodejs20.x
      Handler: hello.handler
      CodeUri: .
      Environment:
        Variables:
          MY_SECRET: '{{resolve:ssm:mySecret1}}'
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway 
            Path: /hello
            Method: GET
  RandomFunction:
    Type: AWS::Serverless::Function
    Condition: ShouldDeployRandom
    Properties:
      Runtime: nodejs20.x
      Handler: random.handler
      CodeUri: .
      Layers:
        - !Ref LambdaLayer
      Events:
        RandomAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway 
            Path: /random
            Method: GET